using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Upgrow.Application.Helper
{
    public static class ApiEndpoints
    {
        #region Sprint Verify Endpoints
        public const string VOTER_VERIFY = "/api/v1/verification/voter_verify";
        public const string DRIVING_LICENCE_V1 = "/api/v1/verification/drivinglicense_verify";
        public const string DRIVING_LICENCE_V2 = "/api/v1/verification/driving_licence_v2";
        public const string GetBalance_ENDPOINT = "/api/v1/verification/getbalance";
        public const string PAN_VERIFY_ENDPOINT = "/api/v1/verification/pan_verify";
        public const string GST_VALIDATE = "/api/v1/verification/gst_verify";
        public const string GST_ADVANCE_V2 = "/api/v1/verification/gst-advance-v2";
        public const string UPLOAD_STATEMENT_ENDPOINT = "/api/v1/verification/bank-statement-analyzer/upload";
        public const string REPORT_FETCH_ENDPOINT = "/api/v1/verification/bank-statement-analyzer/report-fetch";
        public const string BULK_UPLOAD_GST_ENDPOINT = "api/v1/verification/bulk_upload_gst";
        public const string BULK_UPLOAD_RC_ENDPOINT = "api/v1/verification/bulk_upload_rc";
        public const string BANK_ACCOUNT_VERIFY_ENDPOINT = "api/v1/verification/bulk_upload_account";
        public const string CHECK_STATUS = "/api/v1/verification/check_status";
        public const string ENDPOINT = "/api/v1/verification/company_name_to_cin";
        public const string Credit_Report_State_ENDPOINT = "api/v1/verification/credit-report/state-list";
        public const string CREDIT_REPORT_CheckerEX_ENDPOINT = "api/v1/verification/credit-report-checker-ex";
        public const string CreditReportFetchEQ_ENDPOINT = "api/v1/verification/credit_report_checker";
        public const string CRIME_CHECK_INDIVIDUAL_ENDPOINT = "/api/v1/verification/crime-check/individual";
        public const string CRIME_CHECK_COMPANY_ENDPOINT = "/api/v1/verification/crime-check/company";
        public const string CRIME_CHECK_DOWNLOAD_PDF_REPORT_ENDPOINT = "/api/v1/verification/crime-check/download_pdf_report";
        public const string CRIME_CHECK_DOWNLOAD_JSON_REPORT_ENDPOINT = "/api/v1/verification/crime-check/download_json_report";
        public const string Inititate_Session_ENDPOINT = "api/v1/verification/digilocker/initiate_session";
        public const string Access_Token_Generation_ENDPOINT = "/api/v1/verification/digilocker/access_token";
        public const string Issued_Files_Endpoint = "api/v1/verification/digilocker/issued_files";
        public const string Download_Pdf_Endpoint = "api/v1/verification/digilocker/download_pdf";
        public const string Download_Xml_Endpoint = "api/v1/verification/digilocker/download_xml";
        public const string Eaadhaar_Endpoint = "/api/v1/verification/digilocker/eaadhaar";
        public const string TELECOM_VERIFY = "/api/v1/verification/telecom/sendotp";
        public const string TELECOM_GET_DETAILS = "/api/v1/verification/telecom/verifyotp";
        public const string PAISA_DROP_Endpoint = "/api/v1/verification/paisadrop";
        public const string IFSC_LOOKUP_Endpoint = "/api/v1/verification/ifsc_lookup";
        public const string MOBILE_INTELLIGENCE_ENDPOINT = "/api/v1/verification/fetch_personal_profile";
        public const string PINCODE_INFO_ENDPOINT = "/api/v1/verification/pincode_info";
        public const string VPN_PROXY_CHECK_ENDPOINT = "/api/v1/verification/vpn_proxy";
        public const string DIN_VERIFICATION_ENDPOINT = "/api/v1/verification/corporate/din";
        public const string PASSPORT_VERIFY = "/api/v1/verification/passport_verify";
        public const string UDYAM_AADHAAR_V1 = "/api/v1/verification/udyam_aadhaar_verify";
        public const string UDYAM_AADHAAR_V2 = "/api/v1/verification/udyam_aadhaar_verify_v2";
        public const string ITR_COMPLIANCE_CHECK = "/api/v1/verification/itr_check";
        public const string MCA_VERIFY = "/api/v1/verification/mca_verify";
        public const string TAN_VALIDATE = "/api/v1/verification/tan_verify";
        public const string TAN_ADVANCE = "/api/v1/verification/tan-advance";
        public const string STATE_LIST_GET = "/api/v1/verification/getStateList";
        public const string STATE_LIST_DETAILS = "/api/v1/verification/shop_establishment";
        public const string RC_VERIFICATION = "/api/v1/verification/rc_verify";
        public const string RC_ADVANCE_VERIFICATION = "/api/v1/verification/rc_advance";
        public const string REVERSE_RC_VERIFICATION = "/api/v1/verification/reverse-rc";
        public const string IEC_VERIFICATION = "/api/v1/verification/iec_verify";
        public const string FSSAI_VERIFICATION = "/api/v1/verification/fssai_check";
        public const string EMAIL_CHECKER = "/api/v1/verification/email_checker";
        public const string EMAIL_CHECKERV2 = "/api/v1/verification/fssai_check";
        public const string DIN_TO_MOBILE_NUMBER_ENDPOINT = "/api/v1/verification/corporate/director-phone";
        public const string MOBILE_TO_UPI_VPA_ENDPOINT = "/api/v1/verification/mobile_to_upi";
        public const string UAN_BASIC_V1_ENDPOINT = "/api/v1/verification/uan_basic_v1";
        public const string UAN_BASIC_V2_ENDPOINT = "/api/v1/verification/uan_basic_v2";
        public const string LEI_VERIFICATION = "api/v1/verification/lei_verify";
        public const string AADHAAR_QR_CHECK = "/api/v1/verification/aadhaar_qr_check";
        public const string OTP_SEND = "/api/v1/verification/sendOtp";
        public const string VERIFY_OTP = "/api/v1/verification/VerifyOtp";
        public const string PASSPORT_DOWNLOAD = "/api/v1/verification/epfo_passbook_download";
        public const string KYC_DETAILS_GET = "/api/v1/verification/epfo_kyc_fetch";
        public const string EPFO_WITHOUT_OTP = "/api/v1/verification/epfo_without_otp";
        public const string FACE_MATCH = "/api/v1/verification/face_match";
        public const string LIVENESS_CHECK = "/api/v1/verification/liveness_check";
        public const string UPI_VERIFICATION = "/api/v1/verification/upi_verify";
        public const string VEHICLE_CHALLAN_V1 = "/api/v1/verification/chalan_info";
        public const string VEHICLE_CHALLAN_V2 = "/api/v1/verification/challan-info-v2";
        public const string OCR_VALIDATE = "/api/v1/verification/ocr_doc";
        public const string BAV_HYBRID_V1 = "/api/v1/verification/bank_verify";
        public const string BAV_HYBRID_V2 = "/api/v1/verification/bank_verify_v2";
        public const string BAV_HYBRID_V3 = "/api/v1/verification/bank_verify_hybrid_v3";
        public const string BAV_PENNYLESS_V1 = "/api/v1/verification/bank_verify_pennyless";
        public const string BAV_PENNYLESS_V2 = "/api/v1/verification/bank_verify_pennyless_v2";
        public const string BAV_PENNYLESS_V3 = "/api/v1/verification/bank_verify_pennyless_v3";
        public const string BAV_PENNYDROP_V1 = "/api/v1/verification/penny_drop";
        public const string BAV_PENNYDROP_V2 = "/api/v1/verification/penny_drop_v2";
        public const string REVERSE_GEO_LOCATION = "/api/v1/verification/reverse_geocode";
        public const string IP_LOOKUP = "/api/v1/verification/ip_geo_lookup";
        public const string MOBILE_OPERATOR_CHECK = "/api/v1/verification/mobile_operator";
        public const string MOBILE_IMEI_VERIFICATION_ENDPOINT = "/api/v1/verification/imei_verification";
        public const string CARD_VALIDATION_ENDPOINT = "api/v1/verification/card_validator";
        public const string NAME_MATCH_ENDPOINT = "/api/v1/verification/name_match";
        public const string RTO_INFORMATION_ENDPOINT = "/api/v1/verification/rto_info";
        public const string STOCK_PRICE_VERIFICATION_ENDPOINT = "/api/v1/verification/stock_price";
        public const string PAN_TO_GST_ENDPOINT = "/api/v1/verification/pan_to_gst";
        public const string FUEL_PRICE_FETCH_ENDPOINT = "/api/v1/verification/fuel_price";
        public const string TAN_LOOKUP_ENDPOINT = "/api/v1/verification/company_to_tan";
        public const string COURT_CASE_STATUS_ENDPOINT = "/api/v1/verification/court_case_check";
        public const string SINGLE_TWENTY_SIX_AS_DETAILS_ENDPOINT = "/api/v1/verification/get_26as";
        public const string TWENTY_SIX_AS_LIST_ENDPOINT = "/api/v1/verification/26as_list";
        public const string SINGLE_ITR_DETAILS_ENDPOINT = "/api/v1/verification/get_itr";
        public const string ITR_LIST_ENDPOINT = "/api/v1/verification/itr_list";
        public const string PROFILE_GET_ENDPOINT = "/api/v1/verification/it_profile_get";
        public const string ITR_SUBMIT_OTP_ENDPOINT = "/api/v1/verification/itr_submit_otp";
        public const string ITR_FORGET_PASSWORD_ENDPOINT = "/api/v1/verification/itr_forget_password";
        public const string ITR_CREATE_CLIENT_ENDPOINT = "/api/v1/verification/itr_create_client";
        public const string AADHAAR_SENDOTP_ENDPOINT = "/api/v1/verification/aadhaar_sendotp";
        public const string AADHAR_VERIFY_ENDPOINT = "/api/v1/verification/aadhaar_verifyotp";
        #endregion

        #region Sandbox Endpoints

        public const string SB_AADHAR_SENDOTP = "/kyc/aadhaar/okyc/otp";
        public const string SB_AADHAR_VERIFYOTP = "/kyc/aadhaar/okyc/otp/verify";
        public const string SB_PAN_VERIFY = "/kyc/pan/verify";
        public const string SB_PAN_AADHAR_LINK = "/kyc/pan-aadhaar/status";
        public const string SB_SEARCH_GSTIN = "/gst/compliance/public/gstin/search";
        public const string SB_IFSC_VERIFY = "/bank/{ifsc}";
        public const string SB_BANK_ACCOUNT_VERIFY = "/bank/{ifsc}/accounts/{account_number}/verify";
        public const string SB_BANK_ACCOUNT_PENNYLESS_VERIFY = "/bank/{ifsc}/accounts/{account_number}/penniless-verify";

        #endregion


        #region Authenticate Central API Endpoints
        // Sandbox - Central API (forwarded from Public API)
        public const string CENTRAL_AADHAR_SENDOTP = "AadhaarSendOtp";
        public const string CENTRAL_AADHAR_VERIFYOTP = "AadhaarVerifyOtp";
        public const string CENTRAL_PAN_VERIFY = "PanVerify";
        public const string CENTRAL_PAN_AADHAR_LINK = "PanAadhaarLink";
        public const string CENTRAL_SEARCH_GSTIN = "SearchGstIN";
        public const string CENTRAL_IFSC_VERIFY = "IfscVerify";
        public const string CENTRAL_PENNY_DROP_VERIFY = "PennyDropVerify";
        public const string CENTRAL_PENNY_LESS_VERIFY = "PennyLessVerify";
        #endregion
        #region Authenticate Sprint Verify API Endpoints
        // Sprint Verify - Central API (forwarded from Sprint Verify API)
        public const string CENTER_GET_STATE_LIST = "GetStateList";
        public const string CENTER_DRIVING_LICENCE_V1 = "DrivingLicenceV1";
        public const string CENTER_DRIVING_LICENCE_V2 = "DrivingLicenceV2";
        public const string CENTER_QR_CHECK = "QRCheck";
        public const string CENTER_UPLOAD_STATEMENT = "UploadStatement";
        public const string CENTER_REPORT_FETCH = "ReportFetch";
        public const string CENTER_BAV_HYBRID_V1 = "BAVHybridV1";
        public const string CENTER_BAV_HYBRID_V2 = "BAVHybridV2";
        public const string CENTER_BAV_HYBRID_V3 = "BAVHybridV3";
        public const string CENTER_BAV_PENNYLESS_V1 = "BAVPennylessV1";
        public const string CENTER_BAV_PENNYLESS_V2 = "BAVPennylessV2";
        public const string CENTER_BAV_PENNYLESS_V3 = "BAVPennylessV3";
        public const string CENTER_BAV_PENNYPDROP_V1 = "BAVPennydropV1";
        public const string CENTER_BAV_PENNYPDROP_V2 = "BAVPennydropV2";
        public const string CENTER_GST_VERIFY = "GSTVerify";
        public const string CENTER_RC_VERIFY = "RCVerify";
        public const string CENTER_BANK_ACCOUNT_VERIFY = "BankAccountVerify";
        public const string CENTER_CARD_VALIDATION = "CardValidation";
        public const string CENTER_STATUS_CHECK = "StatusCheck";
        public const string CENTER_CONVERT = "Convert";
        public const string CENTER_COURT_CASE_STATUS = "CourtCaseStatus";
        public const string CENTER_STATE = "State";
        public const string CENTER_CREDIT_REPORT_CHECK_EX = "CreditReportCheckEX";
        public const string CENTER_CREDIT_REPORT_FETCH_EQ = "CreditReportFetchEQ";
        public const string CENTER_CRIME_CHECK_INDIVIDUAL = "CrimeCheckIndividual";
        public const string CENTER_CRIME_CHECK_COMPANY = "CrimeCheckCompany";
        public const string CENTER_DOWNLOAD_PDF_REPORT = "DownloadPdfReport";
        public const string CENTER_DOWNLOAD_JSON_REPORT = "DownloadJsonReport";
        public const string CENTER_INITIATE_SESSION = "InitiateSession";
        public const string CENTER_GENERATE_ACCESS_TOKEN = "GenerateAccessToken";
        public const string CENTER_GET_ISSUED_FILES = "GetIssuedFiles";
        public const string CENTER_DOWNLOAD_DOCUMENT_PDF = "DownloadDocumentPdf";
        public const string CENTER_DOWNLOAD_DOCUMENT_XML = "DownloadDocumentXml";
        public const string CENTER_GET_EAADHAAR_XML = "GetEaadhaarXml";
        public const string CENTER_IFSC_LOOKUP = "IFSCLookup";
        public const string CENTER_PROCESS_DROP = "ProcessDrop";
        public const string CENTER_MOBILE_INTELLIGENCE = "MobileIntelligence";
        public const string CENTER_PINCODE_INFO = "PincodeInfo";
        public const string CENTER_VPN_PROXY_CHECK = "VpnProxyCheck";
        public const string CENTER_DIN_VERIFICATION = "DinVerification";
        public const string CENTER_MOBILE_VERIFY = "MobileVerify";
        public const string CENTER_EMAIL_CHECKER = "EmailChecker";
        public const string CENTER_EMAIL_CHECKER_V2 = "EmailCheckerV2";
        public const string CENTER_PASSBOOK_DOWNLOAD = "PassbookDownload";
        public const string CENTER_KYC_DETAILS = "KYCDetails";
        public const string CENTER_EPFO_WITHOUT_OTP = "EPFOWithoutOTP";
        public const string CENTER_FACE_MATCH_VERIFY = "FaceMatchVerify";
        public const string CENTER_IFSSAI_VERIFICATION = "IFSSAIVerification";
        public const string CENTER_FUEL_PRICE_FETCH = "FuelPriceFetch";
        public const string CENTER_GST_ADVANCE_V2 = "GstAdvanceV2";
        public const string CENTER_GST_VALIDATE = "GSTValidate";
        public const string CENTER_IEC_VERIFICATION = "IECVerification";
        public const string CENTER_IP_LOOKUP = "IPLookup";
        public const string CENTER_INCOME_TAX_RETURN = "IncomeTaxReturn";
        public const string CENTER_ITR_CREATE_CLIENT = "ITRCreateClient";
        public const string CENTER_ITR_FORGET_PASSWORD = "ITRForgetPassword";
        public const string CENTER_ITR_LIST = "ITRList";
        public const string CENTER_ITR_SUBMIT_OTP = "ITRSubmitOTP";
        public const string CENTER_LEI_VERIFY = "LEIVerify";
        public const string CENTER_LIVENESS_CHECK = "LivenessCheck";
        public const string CENTER_MAIN_BALANCE = "MainBalance";
        public const string CENTER_MCA_VERIFICATION = "MCAVerification";
        public const string CENTER_MOBILE_IMEI_VERIFICATION = "MobileIMEIVerification";
        public const string CENTER_MOBILE_OPERATOR_CHECK = "MobileOperatorCheck";
        public const string CENTER_MOBILE_TO_UPI_VPA = "MobileToUPIVPA";
        public const string CENTER_NAME_MATCH = "NameMatch";
        public const string CENTER_OCR_UPLOAD = "OCRUpload";
        public const string CENTER_OTP_SEND = "OTPSend";
        public const string CENTER_OTP_VERIFY = "OTPVerify";
        public const string CENTER_VERIFY_PAN = "VerifyPan";
        public const string CENTER_PAN_TO_GST = "PANToGST";
        public const string CENTER_GST_PASSPORT = "GstPassPort";
        public const string CENTER_PROFILE_GET = "ProfileGet";
        public const string CENTER_RC_VERIFICATION = "RCVerification";
        public const string CENTER_RC_ADVANCE_VERIFICATION = "RCAdvanceVerification";
        public const string CENTER_RC_REVERSE_VERIFICATION = "RCReverseVerification";
        public const string CENTER_REVERSE_GEO_LOCATION = "ReverseGeoLocation";
        public const string CENTER_RTO_INFORMATION = "RTOInformation";
        public const string CENTER_SHOP_ESTABLISHMENT_DETAILS = "ShopEstablishmentDetails";
        public const string CENTER_SINGLE_ITR_DETAILS = "SingleITRDetails";
        public const string CENTER_SINGLE_26AS_DETAILS = "Single26ASDetails";
        public const string CENTER_STOCK_PRICE_VERIFICATION = "StockPriceVerification";
        public const string CENTER_TAN_LOOKUP = "TANLookup";
        public const string CENTER_TAN_VERIFY = "TANVerify";
        public const string CENTER_TAN_ADVANCE_VERIFY = "TANAdvanceVerify";
        public const string CENTER_TELECOM_VALIDATE = "TelecomValidate";
        public const string CENTER_TELECOM_GET_DETAILS = "TelecomGetDetails";
        public const string CENTER_26AS_LIST = "26ASList";
        public const string CENTER_UAN_BASIC_V1 = "UANBasicV1";
        public const string CENTER_UAN_BASIC_V2 = "UANBasicV2";
        public const string CENTER_UDYAM_AADHAAR_V1 = "UdyamAadhaarV1";
        public const string CENTER_UDYAM_AADHAAR_V2 = "UdyamAadhaarV2";
        public const string CENTER_UPI_VERIFY = "UPIVerify";
        public const string CENTER_VALIDATE_VOTER_ID = "ValidateVoterId";
        public const string CENTER_VEHICLE_CHALLAN_V1 = "VehicleChallanVerifyV1";
        public const string CENTER_VEHICLE_CHALLAN_V2 = "VehicleChallanVerifyV2";
        public const string CENTER_AADHAR_SEND_OTP = "AadharSendOTP";
        public const string CENTER_AADHAR_VERIFY_OTP = "AadharVerifyOTP";
        #endregion
    }
}
